// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNcq7N8wi4jRTHvbDWrfubZYRFK6rcZB0',
    appId: '1:271442909805:web:707d6da6eab930a0053d64',
    messagingSenderId: '271442909805',
    projectId: 'application-mappital',
    authDomain: 'application-mappital.firebaseapp.com',
    storageBucket: 'application-mappital.firebasestorage.app',
    measurementId: 'G-FE1WQS7622',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS3FvHM8ibmrnJoOS1-PeCHIP7V2fhYak',
    appId: '1:271442909805:android:b320379cccaee0e0053d64',
    messagingSenderId: '271442909805',
    projectId: 'application-mappital',
    storageBucket: 'application-mappital.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATdanbaEadADkWeS-NctQt3vwT4igpkME',
    appId: '1:271442909805:ios:d977e2f2f73aedc0053d64',
    messagingSenderId: '271442909805',
    projectId: 'application-mappital',
    storageBucket: 'application-mappital.firebasestorage.app',
    iosClientId: '271442909805-qledc1p62086k038ocs6kv1netk3h0ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.applicationMappital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATdanbaEadADkWeS-NctQt3vwT4igpkME',
    appId: '1:271442909805:ios:d977e2f2f73aedc0053d64',
    messagingSenderId: '271442909805',
    projectId: 'application-mappital',
    storageBucket: 'application-mappital.firebasestorage.app',
    iosClientId: '271442909805-qledc1p62086k038ocs6kv1netk3h0ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.applicationMappital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNcq7N8wi4jRTHvbDWrfubZYRFK6rcZB0',
    appId: '1:271442909805:web:bac6104f86e564ff053d64',
    messagingSenderId: '271442909805',
    projectId: 'application-mappital',
    authDomain: 'application-mappital.firebaseapp.com',
    storageBucket: 'application-mappital.firebasestorage.app',
    measurementId: 'G-16GZ4S86H4',
  );
}
